spring.application.name=smarttransithub

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/project?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090
 
#JWT cusotm props
jwt.secret.key=2aa8e8d71860a67967a15a52f6285739be20492dcc6353010e948181ddf51375
# exp time in msec 2 hours 
jwt.exp.time=7200000

logging.level.org.springframework.security=TRACE